draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0
    rel_y: 1
    rel_w: 2
    rel_h: 4
    rx: 4
    ry: 6
  svg_extra_style: |
    /**
    * Styles borrowed (with adjustments) from:
    * - https://github.com/SethMilliken/zmk-config/blob/main/keymap_drawer.config.yaml
    * - https://github.com/englmaxi/zmk-config/blob/master/keymap-drawer/config.yaml
    **/

    :root {
      /* smaller font-size than the keymap-drawer default */
      --font-size: 12px;

      /* Color palerte */
      --main-color: #CCCCCC;
      --text-color: #000000;
      --border-color: #000000;
      --held-color: #D1C6E9;
       
      /* Default key colors */
      --key-color: var(--main-color);
      --key-border-color: var(--border-color);
    }

    /* Improve font-family to render properly the combining unicode symbols */
    svg.keymap {
      font-family: Helvetica, Arial, sans-serif;
      font-size: var(--font-size);
      fill: var(--text-color);
    }
    /* Use relative font-size for no main tap key label */
    text.combo, text.hold, text.shifted, text.left, text.right {
      font-size: 0.75em;
    }
    /* Shifted a bit bigger */
    text.shifted {
      font-size: 0.80em;
      translate: 0 0.2em;
    }

    /* Reposition he AltGr labels as they are too close to the rect limit */
    text.key.right {
      /* Also move a bit above the main key label */
      dominant-baseline: auto;
      translate: -0.2em;
    }

    /* Reposition hold labels as they are too close to the key-side */
    text.key.hold {
      translate: 0 -0.5em;
    }

    /* Custom color setup on keys and sides */
    .key {
      /* Same computed color transform as in keymap-layout-editor */
      --key-inner-color: lab(from var(--key-color) min(100, calc(l * 1.2)) a b);
      --key-inner-stroke-color: lab(from var(--key-inner-color) min(80, l) a b);
      rect {
        fill: var(--key-color);
        filter: none;
      }
      rect.key:not(.side) {
        fill: var(--key-inner-color);
        stroke: var(--key-inner-stroke-color);
      }
      /* Border color for keys */
      rect.key.side {
        stroke: var(--key-border-color);
      }
    }

    /* Layer activator styles*/
    .key:has(> a > text:is(.hold.layer-activator)), .key.held {
      --key-color: var(--held-color);
    }

  footer_text: ""
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    # ZMK behaviors
    "&caps_word":
      tap: Caps word
    "&none":
      type: none
    # Bluetooth
    "&bt BT_CLR":
      tap: $$mdi:bluetooth-settings$$
      right: $$mdi:close-thick$$
      hold: Clear
      type: symbol_right_modifier
    "&bt BT_CLR_ALL":
      tap: $$mdi:bluetooth-settings$$
      right: $$mdi:asterisk$$
      hold: Clear All
      type: symbol_right_modifier
    "&bt_0":
      tap: $$mdi:bluetooth-connect$$
      right: "0"
      type: text_right_modifier
    "&bt_1":
      tap: $$mdi:bluetooth-connect$$
      right: "1"
      type: text_right_modifier
    "&bt_2":
      tap: $$mdi:bluetooth-connect$$
      right: "2"
      type: text_right_modifier
    "&bt_3":
      tap: $$mdi:bluetooth-connect$$
      right: "3"
      type: text_right_modifier
    "&out OUT_USB":
      tap: $$mdi:usb$$
      hold: USB
    # RGB
    "&rgb_ug RGB_TOG":
      tap: $$mdi:lightbulb-on-outline$$
      hold: $$mdi:toggle-switch$$
    "&rgb_ug RGB_EFF":
      tap: $$mdi:lightbulb-on-outline$$
      hold: "Effects"
    "&rgb_ug RGB_BRI":
      tap: $$mdi:lightbulb-on-outline$$
      right: "$$mdi:plus$$"
      hold: "Bright"
      type: symbol_right_modifier
    "&rgb_ug RGB_BRD":
      tap: $$mdi:lightbulb-on-outline$$
      right: "$$mdi:minus$$"
      hold: "Bright"
      type: symbol_right_modifier
    "&rgb_ug RGB_SAI":
      tap: $$mdi:lightbulb-on-outline$$
      right: "$$mdi:plus$$"
      hold: "Sat"
      type: symbol_right_modifier
    "&rgb_ug RGB_SAD":
      tap: $$mdi:lightbulb-on-outline$$
      right: "$$mdi:minus$$"
      hold: "Sat"
      type: symbol_right_modifier
    "&rgb_ug RGB_HUI":
      tap: $$mdi:lightbulb-on-outline$$
      right: "$$mdi:plus$$"
      hold: "Hue"
      type: symbol_right_modifier
    "&rgb_ug RGB_HUD":
      tap: $$mdi:lightbulb-on-outline$$
      right: "$$mdi:minus$$"
      hold: "Hue"
      type: symbol_right_modifier
    "&rgb_ug RGB_SPI":
      tap: "$$mdi:lightbulb-on-outline$$"
      right: "$$mdi:plus$$"
      hold: "Speed"
      type: symbol_right_modifier
    "&rgb_ug RGB_SPD":
      tap: "$$mdi:lightbulb-on-outline$$"
      right: "$$mdi:minus$$"
      hold: "Speed"
      type: symbol_right_modifier
    # Reset
    "&bootloader":
      tap: $$mdi:flash$$
      hold: "Boot"
    "&sys_reset":
      tap: $$mdi:restart$$
      hold: "Reset"
    # glove80
    "&lower":
      tap: Lower
      type: glove80_layer_switch
    "&magic LAYER_Magic 0":
      tap: Magic
      type: glove80_layer_switch
    # Custom macros
    "&es_tilde_undead":
      tap: "~"
    "&es_grave_undead":
      tap: "`"
    "&es_caret_undead":
      tap: "^"
    ## TODO: this should be not a raw_binding but rather an alias on the keymap to simplify development
    "&kp LC(ES_C)":
      tap: Copy
    "&kp LC(ES_V)":
      tap: Paste
    "&kp LC(ES_X)":
      tap: Cut
    "&kp LC(ES_Z)":
      tap: Undo
    "&kp LC(ES_Y)":
      tap: Redo
    "&kp LC(ES_F)":
      tap: Find
    "&kp LC(ES_G)":
      tap: Find Next
    "&kp LC(LS(ES_G))":
      tap: Find Prev
    "&kp LC(ES_H)":
      tap: Find and Replace
    "&kp LC(ES_A)":
      tap: Select all
    "&select_none":
      tap: Select none
    "&kp LC(ES_E)":
      tap: Search bar
    "&kp LC(ES_L)":
      tap: URL bar
    "&kp LC(ES_J)":
      tap: Downloads
    "&kp LS(TAB)":
      tap: $$mdi:keyboard-tab-reverse$$
    "&kp LG(ES_DOT)":
      tap: Emoji Picker
  sticky_label: "(sticky)"
  toggle_label: $$mdi:toggle-switch$$
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctrl
    right_ctrl: Ctrl
    left_shift: Shift
    right_shift: Shift
    left_alt: Alt
    right_alt: AltGr
    left_gui: Win
    right_gui: Win
    keycode_combiner: "{mods}+ {key}"
    mod_combiner: "{mod_1}+{mod_2}"
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix:
    # remove the ES_ prefix as they are in use
    - ES_
  zmk_keycode_map:
    # SPANISH KEYS WITH SHIFTED/ALTGR SYMBOLS
    N1:
      tap: 1
      shifted: "!"
      right: "|"
    N2:
      tap: 2
      shifted: '"'
      right: "@"
    N3:
      tap: 3
      shifted: "·"
      right: "#"
    N4:
      tap: 4
      shifted: "$"
      right: "◌̃ "
    N5:
      tap: 5
      shifted: "%"
      right: "€"
    N6:
      tap: 6
      shifted: "&"
      right: "¬"
    N7:
      tap: 7
      shifted: "/"
    N8:
      tap: 8
      shifted: "("
    N9:
      tap: 9
      shifted: ")"
    N0:
      tap: 0
      shifted: "="
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS:
      tap: +
      shifted: "*"
      right: "]"
    MINUS: "-"
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: \
    BSLH: \
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ;
    SEMI: ;
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: "?"
    SQT:
      tap: "'"
      shifted: "?"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA:
      tap: ","
      shifted: ";"
    LESS_THAN: <
    LT:
      tap: "<"
      shifted: ">"
    PERIOD:
      tap: "."
      shifted: ":"
    DOT:
      tap: "."
      shifted: ":"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "◌̀ "
      shifted: "◌̂ "
      right: "["
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
    C_CEDILLA:
      tap: "Ç"
      right: "}"
    N_TILDE: "Ñ"
    IEXCL:
      tap: "¡"
      shifted: "¿"
    ORDM:
      tap: "º"
      shifted: "ª"
      right: '\'
    ACUTE:
      tap: "◌́ "
      shifted: "◌̈ "
      right: "{"
    # MODIFIERS
    LGUI: ⊞ Win
    RGUI: ⊞ Win
    LCTRL: ⎈ Ctrl
    RCTRL: ⎈ Ctrl
    LALT: ⎇ Alt
    RALT: ⎇ AltGr
    LSHFT: ⇧ Shift
    RSHFT: ⇧ Shift
    # NAVIGATION
    LEFT: "$$mdi:arrow-left$$"
    UP: "$$mdi:arrow-up$$"
    RIGHT: "$$mdi:arrow-right$$"
    DOWN: "$$mdi:arrow-down$$"
    LEFT_ARROW: "$$mdi:arrow-left$$"
    UP_ARROW: "$$mdi:arrow-up$$"
    RIGHT_ARROW: "$$mdi:arrow-right$$"
    DOWN_ARROW: "$$mdi:arrow-down$$"
    ESC: "Esc"
    PG_UP: " PgUp"
    PAGE_UP: "PgUp"
    PG_DN: "PgDn"
    PAGE_DOWN: "PgDn"
    HOME: "⇱ Home"
    END: "⇲ End"
    # EDITING
    TAB: "$$mdi:keyboard-tab$$"
    BSPC: "$$mdi:backspace-outline$$"
    DEL: "$$mdi:backspace-reverse-outline$$"
    SPACE: "$$mdi:keyboard-space$$"
    RET: "$$mdi:keyboard-return$$"
    INS: "Ins"
    # LOCK (no numpad)
    CAPS: "⇪ Caps Lock"
    # MEDIA (all except non-windows)
    C_PLAY: "$$mdi:play$$"
    C_PAUSE: "$$mdi:pause$$"
    C_PP: "$$mdi:play-pause$$"
    C_STOP: "$$mdi:stop$$"
    C_PREV: "$$mdi:skip-previous$$"
    C_NEXT: "$$mdi:skip-next$$"
    C_VOL_UP: "$$mdi:volume-plus$$"
    C_VOL_DN: "$$mdi:volume-minus$$"
    C_MUTE: "$$mdi:volume-variant-off$$"
    # BRIGHTNESS (all except non-windows)
    C_BRI_UP:
      tap: "$$mdi:brightness-5$$"
      right: "$$mdi:plus$$"
      type: symbol_right_modifier
    C_BRI_DN:
      tap: "$$mdi:brightness-5$$"
      right: "$$mdi:minus$$"
      type: symbol_right_modifier
    # NUMPAD (all except non-windows)
    KP_NUM: "⇭ Num Lock"
    KP_SLASH: "÷"
    KP_MULTIPLY: "×"
    KP_MINUS: "−"
    KP_PLUS: "+"
    KP_ENTER: Enter
    KP_N0:
      tap: "0"
      shifted: "INS"
    KP_N1:
      tap: "1"
      shifted: "END"
    KP_N2:
      tap: "2"
      shifted: "$$mdi:arrow-down$$"
    KP_N3:
      tap: "3"
      shifted: "PG UP"
    KP_N4:
      tap: "4"
      shifted: "$$mdi:arrow-left$$"
    KP_N5:
      tap: "5"
    KP_N6:
      tap: "6"
      shifted: "$$mdi:arrow-right$$"
    KP_N7:
      tap: "7"
      shifted: "HOME"
    KP_N8:
      tap: "8"
      shifted: "$$mdi:arrow-up$$"
    KP_N9:
      tap: "9"
      shifted: "PG DN"
    KP_DOT:
      tap: "."
      shifted: "DEL"
    # LOWER LAYER (most likely unused)
    PAUSE_BREAK:
      tap: PAUSE
      hold: BREAK
    SCROLLLOCK: "Scroll Lock"
    PRINTSCREEN: "PrtScr"
    K_APP: "≣ Menu"

  zmk_combos: {}
  zmk_preamble: "#define KEYMAP_DRAWER"
  zmk_additional_includes: []
