name: Draw ZMK keymap

on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - draw-config/config.yaml
      - .github/workflows/draw-keymap.yml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write # allow workflow to commit to the repo
    with:
      keymap_patterns: config/*.keymap
      config_path: draw-config/config.yaml
      output_folder: docs/assets
      fail_on_error: true
      # TODO: change to do a commit on release workflow (use also commit_message parameter)
      destination: artifact
      # TODO: currently installing the latest version of keymap-drawer
      # TODO: enable installing a specific version of the tool
